image: node:14-buster

stages:
    - init
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

init:
    stage: init
    script:
        - npm config set registry "https://registry.npm.taobao.org"
        - npm install
    tags:
        - frontend

test:
    stage: test
    script:
        - npm test
    tags:
        - frontend